name: Fraud Detection CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('code/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pandas scikit-learn scipy pytest
    
    - name: Run unit tests
      run: |
        cd code
        pytest tests/ -v --tb=short
    
    - name: Run quick experiment
      run: |
        cd code/scripts
        python run_experiment_simple.py
    
    - name: Generate figures
      run: |
        cd code/eval
        python generate_figures.py
    
    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: experiment-results
        path: |
          results/metrics/
          figures/
    
    - name: Check reproducibility
      run: |
        echo "Verifying results match expected values..."
        python -c "
        import json
        with open('results/metrics/model_comparison.csv') as f:
            print('Results:', f.read())
        "

  docker:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Build Docker image
      run: |
        docker build -t fraud-detection:latest .
    
    - name: Test Docker container
      run: |
        docker run --rm fraud-detection:latest python -c "import sklearn, pandas; print('Container OK')"
    
    - name: Run experiment in container
      run: |
        docker run --rm fraud-detection:latest python code/scripts/run_experiment_simple.py

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install linting tools
      run: |
        pip install flake8 black isort
    
    - name: Run flake8
      run: |
        flake8 code/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 code/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Check code formatting
      run: |
        black --check code/ || echo "Run 'black code/' to format"
